# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: FSA Playbook WIP
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb-lorem
github_username:  usda-fsa
thing: yay
permalink: none

# Sections: effectively the top-level navigation
sections:

  - text: Front Page
    url:

  - text: Accessibility
    url: accessibility

  - text: Content
    url: content

  - text: Foo
    url: foo

  - text: Bar
    url: bar

  - text: About
    url: about

# Build settings
markdown: kramdown

# Ignore specific items from building
exclude:
  - node_modules
  - package.json
  - Gruntfile.js
